# Generated by Django 5.1.1 on 2024-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=15, help_text="Duration in seconds (for videos)"
            ),
        ),
    ]
