# Generated by Django 5.1.1 on 2024-09-15 20:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0003_alter_productmedia_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "mp4", "mov"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="stations", to="screen_app.product"
            ),
        ),
    ]
